# Exported from Render on 2024-10-29T06:41:51Z
services:
- type: web
  name: Blender_Expand
  runtime: python
  repo: https://github.com/hurcaguari/Blender_Expand
  plan: free
  envVars:
  - key: HOST
    value: '0.0.0.0'
  - key: PORT
    value: '8165'
  - key: PYTHONUNBUFFERED
    value: '1'
  - key: PYTHON_VERSION
    value: '3.11.9'
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: sh -c python api.py
  buildFilter:
    ignoredPaths:
    - .vscode
    - data
    - temp
    - expand_data
version: "1"
