schema_version = "1.1.0"
id = "utilities_gadget"
name = "Utilities Gadget"
version = "1.1.0"
tagline = "Utilities Gadget"
maintainer = "INEINST MACH"
type = "add-on"
tags = [ "Mesh",]
blender_version_min = "4.2.0"
license = [ "SPDX:GPL-2.0-or-later",]
website = "https://github.com/hurcaguari/Blender-Utilities-Gadget"
copyright = [ "blender",]
