schema_version = "1.0.0"
id = "Auto_Highlight_in_Outliner"
name = "Auto Highlight In Outliner"
version = "3.8.2"
tagline = "在大纲视图中自动高亮显示选定对象"
maintainer = "xz-blender repack"
type = "add-on"
tags = [ "Object",]
blender_version_min = "4.2.0"
license = [ "SPDX:GPL-2.0-or-later",]
website = "https://blendermarket.com/products/auto-highlight-in-outliner"
copyright = [ "blender",]
wheels = []
