urlpath = "https://blender.hurcaguari.com"
expand_path = "expand_data"
expand_zip = "data"
expand_tmp = "temp"
api_json = "api_json"
updates = 86400

[retry]
retry_ints = 10
retry_interval = 5

[addons.utilities_gadget]
path_type = "git"
path = ""

[addons.auto_highlight_in_outliner]
path_type = "url"
path = "http://blender4.com/add-ons/auto-highlight-in-outliner/3.8.2/download/add-on-auto-highlight-in-outliner-v3.8.2.zip"

[addons.Drop_it]
path_type = "git"
path = ""

[addons.io_scene_max]
path_type = "url"
path = "https://raw.githubusercontent.com/hurcaguari/Blender_Expand/main/__release__/io_scene_max.zip"

[addons.mesh_looptools]
path_type = "url"
path = "https://raw.githubusercontent.com/hurcaguari/Blender_Expand/main/__release__/looptools.zip"

[addons.Quad_Remesher]
path_type = "url"
path = "https://raw.githubusercontent.com/hurcaguari/Blender_Expand/main/__release__/Quad_Remesher.zip"

[addons.LiquiFeel]
path_type = "url"
path = "http://blender4.com/add-ons/liquifeel/1.1.0/download/add-on-liquifeel-v1.1.0.zip"

[addons.FlowProManager]
path_type = "url"
path = "http://blender4.com/add-ons/flowpromanager/4.1.0/download/add-on-flowpromanager-v4.1.0.zip"

[addons.FlaresWizard]
path_type = "url"
path = "http://blender4.com/add-ons/flareswizard/3.2.0/download/add-on-flareswizard-v3.2.0.zip"