schema_version = "1.0.0"
id = "Drop It"
name = "Drop It"
version = "1.2"
tagline = "自动下落目标物体到地面或表面"
maintainer = "Andreas Aust"
type = "add-on"
tags = [ "Object",]
blender_version_min = "4.2.0"
license = [ "SPDX:GPL-3.0 license",]
website = "https://blenderartists.org/t/drop-it-free-addon/1244259"
copyright = [ "Object"]
