schema_version = "1.2.0"
id = "drop_it"
name = "Drop It"
version = "1.2.0"
tagline = "Drop Objects to Ground or Surface"
maintainer = "Andreas Aust"
type = "add-on"
tags = [ "Object",]
blender_version_min = "2.80.0"
license = [ "SPDX:GPL-2.0-or-later",]
website = "https://github.com/hannesdelbeke/drop-it-blender-addon"
copyright = [ "blender",]
