name: Show Environment Variables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  show-env-vars:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: blender_expand
      DOCKER_TAG: latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Show all environment variables
      run: env
