name: Show Environment Variables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  show-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Show all environment variables
      run: env
