name: Run Flask Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Start Flask application
      run: |
        source venv/bin/activate
        nohup python api.py &
    
    - name: Wait for Flask to start
      run: sleep 10

    - name: Call Flask application
      run: |
        curl http://127.0.0.1:8165/
        curl http://127.0.0.1:8165/plugin
        curl http://127.0.0.1:8165/upexpand